# Optional enum parameters shown by `/race create`.
# Change these to the choices supported by your randomizer.
race_start_options:
  - name: Randomizer preset
    value:
      - safe
      - lycan
      - nimble
  - name: Tournament Mode
    value:
      - true
      - false
  - name: Vanilla Music
    value:
      - true
      - false
  - name: Color Rando
    value:
      - true
      - false
  - name: Magic Max
    value:
      - true
      - false
